### ISSUE TITLE
Tranzition

### ISSUE THREAD

**Issue by AlexanderNorway** [NeverHopeless/NHSlideShow#1]
When animation is turned on, image A changes to image B(with animation) and then instantly changes to image C (with no animation). A->BC

**Comment by NeverHopeless** [comment]
Did you press the Next/Previous button when the navigation is about to end ? This sudden change happens when the navigation button presses, at that time slide change occurs but there is no animation takes place at that time. Is this the case you observed ? If it is not, can you please specify necessary steps to reproduce the same behaviour ? Also, which iOS version you are using ?

**Comment by AlexanderNorway** [comment]
It happens even without pressing any buttons (video below) when using Xcode 6.1.1 and 8.1 simulators and on iPhone 6 Plus 8.1.3. When using 7.1 simulators it works perfectly.

Unedited video:
[Youtube](http://youtu.be/X43qMwx8VBY)

**Comment by AlexanderNorway** [comment]
After taking a quick look, one error that I can see is that [[UIScreen mainScreen] bounds] now works differently in iOS 8.
[StackOverflow](http://stackoverflow.com/questions/24150359/is-uiscreen-mainscreen-bounds-size-becoming-orientation-dependent-in-ios8)
Hope this helps!

**Comment by NeverHopeless** [comment]
Currently i do not have required OS setup to run Xcode 6, so i can't test it on version 6. My guess is that this behaviour is due to some bug in NSTimer for iOS8. Probably wrapping function 'beginAnimation' inside 'if(!isAnimating)' should do the job.

-(void)beginAnimation
{
    if(!self.isAnimating)  // If animation is not already in progress.
    {
        [self setUserInteractionEnabled:NO];
        self.isAnimating = YES;

```
    [nextImg setImage:[collection objectAtIndex:otherImageCounter]];

    switch (self.slideShowMode)
    {
        case NHSlideShowModeSwipeLeft:
        {
            [self runSwipeLeftAnimation];
        }break;
        case NHSlideShowModeFade:
        {
            [self runFadeAnimation];
        }break;
        case NHSlideShowModeScale:
        {
            [self runScaleAnimation];
        }break;
        case NHSlideShowModeWindow:
        {
            [self runWindowsAnimation];
        }break;
        case NHSlideShowModeRandom:
        {
            [self runRandomAnimation];
        }break;
        default:
        {

        }break;
    }
}
```

}

I will dig this problem more, once, i have the environment setup. 
Hope it helps!

**EDIT:**
I tested it on XCode 6, it works as expected, after this fix.

**Comment by AlexanderNorway** [comment]
Then I can just close this then :) Thanks!
